name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: Version 1.4.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD}}
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          SLUG: woocommerce-arabic-currencies
