name: Plugin asset/readme update
on:
  push:
    branches:
      - master
jobs:
  master:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD}}
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          SLUG: woocommerce-arabic-currencies
